config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: %i[show edit update]
  get 'translated_articles/show'

  root 'landing#welcome'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :articles
  get 'myarticles', to: 'articles#myarticles'
  get 'article_materials/:id', to: 'article_materials#materials', as: 'article_materials'
  get 'download_material/:id', to: 'article_materials#download_material',
                               as:  'download_material'
  resources :languages
  resources :offers, only: [:show]
  get 'myoffers', to: 'offers#myoffers'
  post 'create_offer', to: 'offers#create', as: 'create_offer'
  put 'accept_offer/:id', to: 'offers#accept_offer', as: 'accept_offer'

  get 'mytasks', to: 'tasks#mytasks'
  resources :tasks, only: [:show]
  put 'complete_translation/:id', to: 'tasks#complete_translation', as: 'complete_translation'
  put 'deny_complete_request/:id', to: 'tasks#deny_complete_request', as: 'deny_complete_request'
  post 'create_translate_order', to: 'translate_orders#create',
                                 as: 'create_translate_order'
  resources :translate_orders, only: %i[show index]
  get 'article_translate_orders/:id', to: 'translate_orders#article_translate_orders',
                                      as: 'article_translate_orders'
  get 'my_translate_orders', to: 'translate_orders#my_translate_orders',
                             as: 'my_translate_orders'
  resources :translated_articles, only: [:show]
  get 'translated_languages/:id', to: 'translated_articles#translated_languages', as: 'translated_languages'
  resources :version_trackers, only: [:show]
  post 'create_version_tracker', to: 'version_trackers#create',
                                 as: 'create_version_tracker'
  resources :version_tracker_materials, only: [:show]
  get "download_version_tracker_material/:id", to: 'version_tracker_materials#download_material',
                                               as: 'download_version_tracker_material'
  resources :version_tracker_comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  extend Enumerize
  enumerize :status, in: { in_progress: 0, done: 1, pending_approval: 2 }
  belongs_to :offer
  belongs_to :translated_article
  belongs_to :translator, foreign_key: 'translator_id', class_name: 'User'
  belongs_to :owner, foreign_key: 'owner_id', class_name: 'User'
  belongs_to :target_language, foreign_key: 'target_language_id', class_name: 'Language'
  belongs_to :source_language, foreign_key: 'source_language_id', class_name: 'Language'
  has_many :version_trackers, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_task, only: %i[show complete_translation deny_complete_request]
  before_action :set_version_trackers, only: [:show]

  def show
    redirect_to root_path unless user_authorized?
  end

  def mytasks
    @tasks = current_user.tasks
  end

  def complete_translation # TODO/ GUVENLIK ONLEMI AL
    @task.in_progress? ? @task.pending_approval! : @task.done!
    redirect_back(fallback_location: :back)
  end

  def deny_complete_request
    @task.in_progress!
    redirect_back(fallback_location: :back)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_version_trackers
    @version_trackers = @task.version_trackers.order('created_at DESC')
  end

  def user_authorized?
    current_user == @task.translator || (current_user == @task.owner)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_belongs_to_user?(task, current_user)
    task.translator == current_user
  end
end

app/views/tasks/mytasks.html.erb
<h1> Çeviri Görevlerim </h1>
<% @tasks.each do |task| %>
 İlgili Görev: <%= link_to task.translated_article.article.name, task_path(task) %> <br>
 Çeviri Durumu :  <%= task.status%> <br> 
<% end %>

app/views/tasks/show.html.erb
<h1>Çeviri Görevi</h1>

Durum: <%= @task.status %> <br>
<% if current_user == @task.translator && @task.in_progress?  %>
  <button class="btn btn-warning"><%= link_to "Çeviriyi Tamamla", complete_translation_path(@task), method: :put, style: "color: white" %>
  </button>  
<% elsif current_user == @task.owner && @task.pending_approval? %>
  <button class="btn btn-warning"><%= link_to "Çeviriyi Tamamla", complete_translation_path(@task), method: :put, style: "color: white" %>
  </button> <br>
  <button class="btn btn-danger">
  <%= link_to "Bitirme İsteğini Reddet", deny_complete_request_path(@task), method: :put, style: "color: white" %>
  </button>
<% end %>

<h3>Versiyonlar</h3>
<% @task.version_trackers.each do |version_tracker| %>
  Versiyon Adı:<%= link_to version_tracker.name, version_tracker_path(version_tracker) %> <br>
  Açıklama:<%= version_tracker.description %> <br> <br>
<h4>Yorum Yap</h4>
  <% version_tracker.version_tracker_comments.each do |version_tracker_comment| %>
    <h5><b> <%= version_tracker_comment.content %> <br>
    <%= version_tracker_comment.created_at.strftime("%d/%m/%Y") %> <br>
    <%= link_to version_tracker_comment.user.email, profile_path(version_tracker_comment.user) %> </b></h5> <br>
  <% end %>
    <%= render partial: 'version_tracker_comments/form', locals: {version_tracker: version_tracker} %>
<% end %>

<% if task_belongs_to_user?(@task, current_user) %>
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#create_version_tracker">Yeni Versiyon Ekle</button>
<% end %>

<%= render "version_trackers/form" %>