config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: %i[show edit update]
  get 'translated_articles/show'

  root 'landing#welcome'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :articles
  get 'myarticles', to: 'articles#myarticles'
  get 'article_materials/:id', to: 'article_materials#materials', as: 'article_materials'
  get 'download_material/:id', to: 'article_materials#download_material',
                               as:  'download_material'
  resources :languages
  resources :offers, only: [:show]
  get 'myoffers', to: 'offers#myoffers'
  post 'create_offer', to: 'offers#create', as: 'create_offer'
  put 'accept_offer/:id', to: 'offers#accept_offer', as: 'accept_offer'

  get 'mytasks', to: 'tasks#mytasks'
  resources :tasks, only: [:show]
  put 'complete_translation/:id', to: 'tasks#complete_translation', as: 'complete_translation'
  put 'deny_complete_request/:id', to: 'tasks#deny_complete_request', as: 'deny_complete_request'
  post 'create_translate_order', to: 'translate_orders#create',
                                 as: 'create_translate_order'
  resources :translate_orders, only: %i[show index]
  get 'article_translate_orders/:id', to: 'translate_orders#article_translate_orders',
                                      as: 'article_translate_orders'
  get 'my_translate_orders', to: 'translate_orders#my_translate_orders',
                             as: 'my_translate_orders'
  resources :translated_articles, only: [:show]
  get 'translated_languages/:id', to: 'translated_articles#translated_languages', as: 'translated_languages'
  resources :version_trackers, only: [:show]
  post 'create_version_tracker', to: 'version_trackers#create',
                                 as: 'create_version_tracker'
  resources :version_tracker_materials, only: [:show]
  get "download_version_tracker_material/:id", to: 'version_tracker_materials#download_material',
                                               as: 'download_version_tracker_material'
  resources :version_tracker_comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/version_tracker.rb
class VersionTracker < ApplicationRecord
  belongs_to :task
  has_many :version_tracker_materials, dependent: :destroy
  has_many :version_tracker_comments, dependent: :destroy
  accepts_nested_attributes_for :version_tracker_materials
end

app/controllers/version_trackers_controller.rb
class VersionTrackersController < ApplicationController
  before_action :set_version_tracker, only: [:show]

  def show; end

  def create
    @version_tracker = VersionTracker.new(version_tracker_params)
    @version_tracker.version_tracker_materials.build(version_tracker_material_params)
    
    if @version_tracker.save
      redirect_to task_path(@version_tracker.task_id)
    else
      redirect_to task_path(@version_tracker.task_id)
    end
  end

  private

  def version_tracker_params
    params.require(:version_tracker).permit(:name, :description, :task_id)
  end

  def set_version_tracker
    @version_tracker = VersionTracker.find(params[:id])
  end

  def version_tracker_material_params
    params.require(:version_tracker)
          .permit(version_tracker_material:
                  %i[description material])[:version_tracker_material]
  end
end

app/helpers/version_trackers_helper.rb
module VersionTrackersHelper
end

app/views/version_trackers/_form.html.erb
<!-- Modal -->
<div id="create_version_tracker" class="modal fade" role="dialog">
 <div class="modal-dialog">
   <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">İstek Oluştur</h4>
    </div>
    <div class="modal-body">
     <%= simple_form_for(@task.version_trackers.build, url: create_version_tracker_path, method: 'post') do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :task_id, as: 'hidden', input_html: { value: @task.id} %>
        <%= f.simple_fields_for :version_tracker_material do |m| %>
          <%= m.input :description %>
          <%= m.input :material, as: :file %>
        <% end %>
        <%= f.button :submit, class: "btn btn-success" %>
     <% end %>      
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#create_version_tracker">Vazgeç</button>
    </div>
   </div>
  </div>
 </div>

app/views/version_trackers/show.html.erb
<h3><%= @version_tracker.name %></h3>

<%= @version_tracker.description %>
<% @version_tracker.version_tracker_materials.each do |version_tracker_material| %>
  <%= version_tracker_material.description %>
  <%= link_to "İndir",  download_version_tracker_material_path(version_tracker_material) %>
<% end %>