config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: %i[show edit update]
  get 'translated_articles/show'

  root 'landing#welcome'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :articles
  get 'myarticles', to: 'articles#myarticles'
  get 'article_materials/:id', to: 'article_materials#materials', as: 'article_materials'
  get 'download_material/:id', to: 'article_materials#download_material',
                               as:  'download_material'
  resources :languages
  resources :offers, only: [:show]
  get 'myoffers', to: 'offers#myoffers'
  post 'create_offer', to: 'offers#create', as: 'create_offer'
  put 'accept_offer/:id', to: 'offers#accept_offer', as: 'accept_offer'

  get 'mytasks', to: 'tasks#mytasks'
  resources :tasks, only: [:show]
  put 'complete_translation/:id', to: 'tasks#complete_translation', as: 'complete_translation'
  put 'deny_complete_request/:id', to: 'tasks#deny_complete_request', as: 'deny_complete_request'
  post 'create_translate_order', to: 'translate_orders#create',
                                 as: 'create_translate_order'
  resources :translate_orders, only: %i[show index]
  get 'article_translate_orders/:id', to: 'translate_orders#article_translate_orders',
                                      as: 'article_translate_orders'
  get 'my_translate_orders', to: 'translate_orders#my_translate_orders',
                             as: 'my_translate_orders'
  resources :translated_articles, only: [:show]
  get 'translated_languages/:id', to: 'translated_articles#translated_languages', as: 'translated_languages'
  resources :version_trackers, only: [:show]
  post 'create_version_tracker', to: 'version_trackers#create',
                                 as: 'create_version_tracker'
  resources :version_tracker_materials, only: [:show]
  get "download_version_tracker_material/:id", to: 'version_tracker_materials#download_material',
                                               as: 'download_version_tracker_material'
  resources :version_tracker_comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/translate_order.rb
class TranslateOrder < ApplicationRecord
  belongs_to :user
  belongs_to :article
  belongs_to :target_language, foreign_key: 'target_language_id', class_name: 'Language'
  belongs_to :source_language, foreign_key: 'source_language_id', class_name: 'Language'
  has_many :offers, dependent: :destroy
  #validates_uniqueness_of :source_language_id, scope: :target_language_id
end

app/controllers/translate_orders_controller.rb
class TranslateOrdersController < ApplicationController
  before_action :authenticate_user!, only: [:my_translate_orders]
  before_action :set_translate_order, only: [:show]
  before_action :set_offers, only: [:show]
  before_action :set_article, only: [:article_translate_orders]

  def index
    @translate_orders = TranslateOrder.all.order('created_at DESC')
  end

  def show; end

  def my_translate_orders
    @translate_orders = current_user.translate_orders
  end

  def create
    @translate_order = TranslateOrder.new(translate_order_params)

    if @translate_order.save
      redirect_to article_path(params[:translate_order][:article_id])
    else
      redirect_to article_path(params[:translate_order][:article_id])
    end
  end

  def article_translate_orders
    @translate_orders = @article.translate_orders
  end

  private

  def translate_order_params
    params.require(:translate_order)
          .permit(:title, :description, :price, :target_language_id,
                  :source_language_id, :user_id, :article_id)
  end

  def set_translate_order
    @translate_order = TranslateOrder.find(params[:id])
  end

  def set_offers
    @offers = @translate_order.offers.order('created_at DESC')
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/translate_orders_helper.rb
module TranslateOrdersHelper

  def order_belongs_to_user?(translate_order, current_user)
    translate_order.user == current_user
  end
end

app/views/translate_orders/_form.html.erb
<div id="create_translate_order" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Çeviri İlanı Oluştur</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(article.translate_orders.build, url: create_translate_order_path, method: 'post') do |f| %>
          <%= f.label "İlan Başlığı" %>
          <%= f.input :title, label: false %>
          <%= f.label "Açıklama" %>
          <%= f.input :description, label: false %>
          <%= f.label "Teklif Edilen Ücret" %>
          <%= f.input :price, label:false %>
          <%= f.label "Çevrilmesi İstenilen Dil" %> <br>
          <%= f.select :target_language_id, all_languages.map {|language| [language.name, language.id]} %> </br><br>
          <%= f.input :source_language_id, as: 'hidden', input_html: { value: article.language_id} %>
          <%= f.input :user_id, as: 'hidden', input_html: { value: article.user_id} %>
          <%= f.input :article_id, as: 'hidden', input_html: { value: article.id} %>
          <%= f.button :submit, "İlan Oluştur", class: "btn btn-success" %>
        <% end %>      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#create_translate_order">Vazgeç</button>
      </div>
    </div>
  </div>
</div>

app/views/translate_orders/_translate_orders.html.erb
<h1><b>İlanlar</b></h1>
<hr class="divider">
<% translate_orders.each do |translate_order| %>
	<% @zanata_project_url =  zanata_project_url(translate_order.article.project_id, translate_order.article.article_materials.first.material.original_filename) %>
	<div class="panel panel-default">
	    <div class="panel-body">
	      <div class="col-md-9">
	          <h1><b><%= translate_order.title %></b></h1>
	          <h3><%= translate_order.description %></h3>
	          <h5>Çeviri Ücreti: <b><%= translate_order.price %></b><i class="fas fa-lira-sign"></i></h5> 
	          <h5>Kaynak Dil: <b><%= translate_order.source_language.name %></b></h5>
	          <h5>Hedef Dil: <b><%= translate_order.target_language.name %></b></h5> 
	      </div> 
	      <div class="col-md-3">
	      <h3><b>İlan Sahibi</b></h3> 
	      <%= image_tag translate_order.user.profile.avatar.url, size: 100 %>
	      <h4><%=  link_to translate_order.user.profile.full_name, profile_path(translate_order.user) %></h4>
	      </div>
	      <div class="col-md-9">  
	            <button class= 'btn btn-primary btn-lg'><%= link_to 'Projeye Git', @zanata_project_url, {target: '_blank', style: 'color:white'} %></button>
	            <% unless order_belongs_to_user?(translate_order, current_user) %>
	                <button type="button" class="btn btn-info btn-lg"><%= link_to 'Teklif Ver', translate_order_path(translate_order), {style: 'color:white'} %></button> <br><br>
	            <% end %>
	      </div>
	      <div class="col-md-3">
	        <h4>Bu ilan <b><%= translate_order.created_at.to_date %></b> tarihinde oluşturuldu</h4>
	      </div>
	  </div>
	</div>
<% end %>

app/views/translate_orders/article_translate_orders.html.erb
<%= render partial: 'articles/article', locals: {article: @article} %> <br><br>
<h1>Çeviri İlanları</h1> 
<% @translate_orders.each do |translate_order| %>
 <%= link_to translate_order.title, translate_order_path(translate_order) %> <br>
 <%= translate_order.description %> <br>
 <%= translate_order.price %> <br>
 <%= translate_order.source_language.name %> <br>
 <%= translate_order.target_language.name %>
<% end %>
<%= render partial: 'form', locals: {article: @article} %>

app/views/translate_orders/index.html.erb
<%= render partial: "translate_orders", locals: {translate_orders: @translate_orders} %>

app/views/translate_orders/my_translate_orders.html.erb
<%= render partial: "translate_orders", locals: {translate_orders: @translate_orders} %>

app/views/translate_orders/show.html.erb
<% @zanata_project_url =  zanata_project_url(@translate_order.article.project_id, @translate_order.article.article_materials.first.material.original_filename) %>
<div class="panel panel-default">
    <div class="panel-body">
      <div class="col-md-9">
          <h1><b><%= @translate_order.title %></b></h1>
          <h3><%= @translate_order.description %></h3>
          <h5>Çeviri Ücreti: <b><%= @translate_order.price %></b><i class="fas fa-lira-sign"></i></h5> 
          <h5>Kaynak Dil: <b><%= @translate_order.source_language.name %></b></h5>
          <h5>Hedef Dil: <b><%= @translate_order.target_language.name %></b></h5> 
      </div> 
      <div class="col-md-3">
      <h3><b>İlan Sahibi</b></h3> 
      <%= image_tag @translate_order.user.profile.avatar.url, size: 100 %>
      <h4><%=  link_to @translate_order.user.profile.full_name, profile_path(@translate_order.user) %></h4>
      </div>
      <div class="col-md-9">  
            <button class= 'btn btn-primary btn-lg'><%= link_to 'Projeye Git', @zanata_project_url, {target: '_blank', style: 'color:white'} %></button>
            <% unless order_belongs_to_user?(@translate_order, current_user) %>
                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#create_translate_order">Teklif Ver</button> <br><br>
            <% end %>
      </div>
      <div class="col-md-3">
        <h4>Bu ilan <b><%= @translate_order.created_at.to_date %></b> tarihinde oluşturuldu</h4>
      </div>
  </div>
</div>




<div class="panel panel-default">
    <div class="panel-body">
      <h2>Bu proje için  <b><%= @offers.count %></b> adet teklif bulunuyor</h2>
      <hr class="divider">
      <% @offers.each do |offer| %>
        <div class="col-md-4">
            <%= image_tag offer.translator.profile.avatar.url, size: 100, style: "background-color: white" %>
        </div>
        <div class="col-md-4">
            <h3><b><%= link_to offer.translator.profile.zanata_username, profile_path(offer.translator) %></b></h3>
            <h5><%= offer.description %></h5>
        </div>
        <div class="col-md-4">
            <h5><b><%= offer.translation_time %> gün içinde <%= offer.price %></b><i class="fas fa-lira-sign"></i>

</h5>
            <h5>Teklif Tarihi:<b> <%= offer.created_at.strftime("%d/%m/%Y") %></b></h6> <br>
        <% if order_belongs_to_user?(@translate_order, current_user) && !(offer.accepted?) %>  
          <button class= "btn btn-success"><%= link_to "Teklifi Kabul Et", accept_offer_path(offer), method: 'put', style: "color: white; text-decoration: none"%>
          </button>
        <% elsif order_belongs_to_user?(@translate_order, current_user) && offer.accepted? %>
          <h4> Teklif Kabul Edildi </h4>
        <% end %> <br> <br>
        </div>
      <% end %>
    </div>
</div>

<%= render 'offers/form' %>