config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: %i[show edit update]
  get 'translated_articles/show'

  root 'landing#welcome'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :articles
  get 'myarticles', to: 'articles#myarticles'
  get 'article_materials/:id', to: 'article_materials#materials', as: 'article_materials'
  get 'download_material/:id', to: 'article_materials#download_material',
                               as:  'download_material'
  resources :languages
  resources :offers, only: [:show]
  get 'myoffers', to: 'offers#myoffers'
  post 'create_offer', to: 'offers#create', as: 'create_offer'
  put 'accept_offer/:id', to: 'offers#accept_offer', as: 'accept_offer'

  get 'mytasks', to: 'tasks#mytasks'
  resources :tasks, only: [:show]
  put 'complete_translation/:id', to: 'tasks#complete_translation', as: 'complete_translation'
  put 'deny_complete_request/:id', to: 'tasks#deny_complete_request', as: 'deny_complete_request'
  post 'create_translate_order', to: 'translate_orders#create',
                                 as: 'create_translate_order'
  resources :translate_orders, only: %i[show index]
  get 'article_translate_orders/:id', to: 'translate_orders#article_translate_orders',
                                      as: 'article_translate_orders'
  get 'my_translate_orders', to: 'translate_orders#my_translate_orders',
                             as: 'my_translate_orders'
  resources :translated_articles, only: [:show]
  get 'translated_languages/:id', to: 'translated_articles#translated_languages', as: 'translated_languages'
  resources :version_trackers, only: [:show]
  post 'create_version_tracker', to: 'version_trackers#create',
                                 as: 'create_version_tracker'
  resources :version_tracker_materials, only: [:show]
  get "download_version_tracker_material/:id", to: 'version_tracker_materials#download_material',
                                               as: 'download_version_tracker_material'
  resources :version_tracker_comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/translated_article.rb
class TranslatedArticle < ApplicationRecord
  belongs_to :article
  belongs_to :language
  has_many :tasks, dependent: :destroy

  def self.exist?(article_id, language_id)
    TranslatedArticle.where(article_id: article_id, language_id: language_id).any?
  end
end

app/controllers/translated_articles_controller.rb
class TranslatedArticlesController < ApplicationController
  before_action :set_translated_article, only: [:show]
  before_action :set_article, only: [:translated_languages]
  def show; end

  def translated_languages
    @translated_articles = @article.translated_articles
  end

  private

  def set_translated_article
    @translated_article = TranslatedArticle.find(params[:id])
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/translated_articles_helper.rb
module TranslatedArticlesHelper
end

app/views/translated_articles/show.html.erb
<h1><%= @translated_article.language.name %></h1>
<h3>Çeviriler</h3>
<% @translated_article.tasks.each do |task| %>
  <%= task.translator.email %> <br>
  <%= task.status %> <br>
  <%= task.source_language.name %> <br>
  <%= task.target_language.name %> <br>
  <%= link_to "Çeviriye Git", task_path(task) %> <br>
  <%= link_to "İlgili Teklif", offer_path(task.offer.id) %> <br>
<% end %>

app/views/translated_articles/translated_languages.html.erb
<%= render partial: 'articles/article', locals: {
                                        article: @article}%>
<%= render partial: 'translate_orders/form', locals: {article: @article} %>
<h3>Versiyonlar</h3>
<% @translated_articles.each do |translated_article| %>
 <%= link_to translated_article.language.name, translated_article_path(translated_article) %>
<% end %>